config/routes.rb
Rails.application.routes.draw do

  resources :tags

  resources :bicycles do
    resources :tags
    member do
      get :compare
    end
  end

  root "bicycles#index"

end

app/models/bicycle.rb
class Bicycle < ActiveRecord::Base
  validates :name, presence: true
  has_many :tags, dependent: :destroy 

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :bicycles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  before_action :set_bicycle, only: [ :edit, :update, :destroy]

  def index
    @bicycles = Bicycle.all
  end

  def compare
  end

  def show
    @bicycle = Bicycle.find(params[:id])
    @tag = Tag.new
  end

  def new
    @bicycle = Bicycle.new
  end

  def edit
  end

  def create
    @bicycle = Bicycle.new(bicycle_params)

    respond_to do |format|
      if (@bicycle.name == "Admin" || @bicycle.name == "weenus")
        format.html { redirect_to bicycles_url }
      end
      if @bicycle.save
        format.html { redirect_to @bicycle, notice: "#{@bicycle.name} was successfully created." }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bicycle.update(bicycle_params)
        format.html { redirect_to @bicycle, notice: "#{@bicycle.name} was successfully updated." }
        format.json { render :index, status: :ok, location: @bicycle }
      else
        format.html { render :edit }
        format.json { render json: @bicycle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bicycle.destroy
    respond_to do |format|
      format.html { redirect_to bicycles_url, notice: "#{@bicycle.name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_bicycle
    @bicycle = Bicycle.find(params[:id])
  end

  def bicycle_params
    params.require(:bicycle).permit(:name, :model, :year, :make)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
    @tag = @bicycle.tags.find(params[:id])
  end

  def show
    @bicycle = Bicycle.find(params[:id])
    @tag = @bicycle.tags.find(params[:id])
  end

  def new
    @bicycle = Bicycle.find(params[:bicycle_id])
    @tag = @bicycle.tags.new
  end

  def edit
    @bicycle = Bicycle.find(params[:bicycle_id])
    @tag = @bicycle.tags.find(params[:id])
  end

  def create
    @bicycle = Bicycle.find(params[:bicycle_id])
    @tag = @bicycle.tags.create(params[:id].permit(:name, :content))
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to bicycle_path(@bicycle), notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @bicycle }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @bicycle = Bicycle.find(params[:bicycle_id])
    @tag = @bicycle.tags.find(params[:id])
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @bicycle.sighting, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bicycle = Bicycle.find(params[:bicycle_id])
    @tag = @bicycle.tags.find(params[:id])
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to bicycle_path(@bicycle), notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/bicycles/_edit.html.erb
<h1>Editing Bicycle <%= "#{@bicycle.name}" %></h1>

<%= render 'form' %>

<%= link_to 'Show', @bicycle %>

app/views/bicycles/_form.html.erb
<%= form_for(@bicycle) do |f| %>
  <% if @bicycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bicycle.errors.count, "error") %> prohibited this bicycle from being saved:</h2>

      <ul>
      <% @bicycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bicycles/_new.html.erb
<h1>New Bicycle</h1>

<%= render 'form' %>

app/views/bicycles/compare.html.erb
placeholder

app/views/bicycles/edit.html.erb
<h1>Editing Bicycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @bicycle %> |

app/views/bicycles/edit.js.erb
debugger;
var dialog = $('#dialog')
dialog.html('<%= escape_javascript(render partial: 'edit.html.erb', locals: {bicycle: @bicycle}).html_safe %>')
dialog.dialog('open')

app/views/bicycles/index.html.erb
<!-- <p id="notice"><%= notice %></p>
 -->
<div id="bacon">
ADD NEW BICYCLE ----->

  <button>
    <%= link_to image_tag("image123.png", height: "100", width: "100"), new_bicycle_path, remote: true %>
  </button>

  <div id="bacon1">
    just a test for alignment soon be an edit button here
    </div>

</div>
<hr>
<% if @bicycles.any? %>

  <h2 align="center">Listing Bicycles Created</h2>
  <br>
<div class="CSSTableGenerator" >
  <table>
    <tbody>
      <td>Name</td>
      <td>Model</td>
      <td>Year</td>
      <td>Make</td>
      <td>Show this bike</td>
      <td>Edit</td>
      <td>Delete</td>
      <% @bicycles.each do |bicycle| %>
      <tr>
        <td><%= bicycle.name %></td>
        <td><%= bicycle.model %></td>
        <td><%= bicycle.year %></td>
        <td><%= bicycle.make %></td>
        <td><button><%= link_to 'Show', bicycle %></button></td>
        <td><button><%= link_to 'Edit', edit_bicycle_path(bicycle), remote: true %></button></td>
        <td><button><%= link_to 'Destroy', bicycle, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
      <% end %>
    </tbody>
    </tr>
  </table>
</div>


<% end %>

app/views/bicycles/new.html.erb
<%= render partial: 'new', locals: {bicycle: @bicycle} %>

app/views/bicycles/new.js.erb
debugger;
var dialog = $('#dialog')
dialog.html('<%= escape_javascript(render partial: 'new.html.erb', locals: {bicycle: @bicycle}).html_safe %>')
dialog.dialog('open')

app/views/bicycles/show.html.erb
<div id="content">

<p id="notice"><%= notice %></p>

<% if (@bicycle.name == "cheese") %>
  <%= "secret password entered" %>
  <br>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @bicycle.name %>
</p>

<p>
  <strong>Model:</strong>
  <%= @bicycle.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @bicycle.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @bicycle.make %>
</p>

<div>
  <div id="div1">

    <h2><%= @bicycle.tags.count %> tags for this bicycle |
    <%= link_to "Add a new tag", new_bicycle_tag_path(@bicycle) %></h2>

  </div>

  <%= render @bicycle.tags %>

</div>

<button> <%= link_to 'Edit', edit_bicycle_path(@bicycle) %> </button> |
<button> <%= link_to 'Back', bicycles_path %> </button> |
<button> <%= link_to 'Add a components tag to this bicycle', new_bicycle_tag_path(@bicycle) %></button>

</div>

app/views/bicycles/similar.html.erb
placeholder text to test the route out...
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bpdia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <link rel="stylesheet" href="/resources/demos/style.css">

</head>
<body>
<header>
  <h1>
    Bikepedia.1
  </h1>
</header>
  <hr>
<div id="content">



  <%= yield -%>
<br>
<br>
  <p align="center", id="notice"><%= notice %></p>
</div>

<!-- I don't know where to keep this dialog div but it is realy important right now that it is in the app.. -->
<div id="dialog" title="Information">
</div>

</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.content %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tag.content %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>